name = "fuelprices-api-cf"
main = "src/index.ts"
compatibility_date = "2023-03-18"

route = { pattern = "fuelprices-api.bjarke.xyz", custom_domain = true }

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "fuelprices_db"
database_id = "34aa415c-25d3-4971-b46b-372ca2d7f0ba"

[triggers]
crons = ["*/30 10-16 * * *"]