name: Deploy

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_WORKER_TOKEN }}
      - name: Notify on error
        uses: fjogeleit/http-request-action@v1
        if: failure() && steps.publish.outcome == 'failure'
        with:
          url: "${{ secrets.NOTIFICATIONS_URL }}"
          method: "POST"
          username: "${{ secrets.NOTIFICATIONS_USERNAME }}"
          password: "${{ secrets.NOTIFICATIONS_PASSWORD }}"
          data: '{ "channels": ["discord", "email"], "message": { "message": "⚠️ ${{ github.repository }} failed to release. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>" } }'
      - name: Notify on success
        uses: fjogeleit/http-request-action@v1
        if: success() && steps.publish.outcome == 'success'
        with:
          url: "${{ secrets.NOTIFICATIONS_URL }}"
          method: "POST"
          username: "${{ secrets.NOTIFICATIONS_USERNAME }}"
          password: "${{ secrets.NOTIFICATIONS_PASSWORD }}"
          data: '{ "channels": ["discord", "email"], "message": { "message": "🚀 ${{ github.repository }} has been released. <https://github.com/${{ github.repository }}/>" } }'
